stages:
  prepare:
    cmd: python src/prepare.py data/ENB2012_data.csv
    params:
    - prepare.test_size
    - seed
    deps:
    - data/ENB2012_data.csv
    - src/prepare.py
    outs:
    - data/prepared
