stages:
  prepare:
    cmd: python src/prepare.py data/ENB2012_data.csv
    params:
    - prepare.test_size
    - seed
    deps:
    - data/ENB2012_data.csv
    - src/prepare.py
    outs:
    - data/test.csv
    - data/train.csv
  xgboost_training:
    cmd: python src/xgboost_train.py
    deps:
    - data/train.csv
    - src/xgboost_train.py
    outs:
    - models/xgboost.joblib
  xgboost_evaluation:
    cmd: python src/evaluate.py models/xgboost.joblib
    deps:
    - data/test.csv
    - src/evaluate.py
    metrics:
    - metrics/metrics.json
    plots:
    - plots
